### ISSUE TITLE
I get 500 Server internal errors

### ISSUE THREAD

**Issue by konstantinkuehn** [Daniel-Brum/hacknplan-discord-integration#1]
I did how described in the readme but receive 500 errors from my server.
Is there any requirement for the webserver to support the scripts ?
![image](https://user-images.githubusercontent.com/43268016/113399012-cc346100-939f-11eb-90f7-ede1a1f49414.png)

**Comment by Daniel-Brum** [comment]
The webserver needs to use PHP 5 >= 5.2.0, PHP 7 or PHP 8, and libcurl >= 7.10.5; I'll commit a simple .php file for quick testing. By navigating its page on your server you can check if it meets the requirements.

**Comment by Daniel-Brum** [comment]
Done! I've commited the test file just now [(031212e)](https://github.com/Daniel-Brum/hacknplan-discord-integration/commit/031212e9d60119009ea6dac71a7283d392ea727c). Just navigate to it in your webserver in order to check if you meet the requirements. Hope that helps!

**Comment by konstantinkuehn** [comment]
It seems like it supports both but still has only 500 internal server errors. ? 

> Does the server use a supported PHP version? Yes Does the server use a supported cURL version? Yes

**Comment by Daniel-Brum** [comment]
Hm... I see.

500 Internal Server errors mean that something went wrong on the server, but aren't specific enough to allow one to find out what's the real problem without taking a look at the logs. If your webserver allows you to see error logs, you can feel free to show me one of them and I can try to figure out what went wrong.
But if that's not the case, the only solution I can possibly think of at the moment is using another webserver.

**Comment by ReturnTypeVoid** [comment]
Just commenting here for visibility; two things:

1) I can't thank you enough for this, and I can't believe this functionality isn't already implemented into HacknPlan, but what you've done is fantastic.

2) I was having this problem, but as you rightly said, it's because the curl module wasn't installed. (Hopefully other users will see this)

Nginx 1.22.0 / PHP 8.1 and it works flawlessly.

**Comment by Daniel-Brum** [comment]
Thanks a lot for commenting here and for confirming that it's working! I think I'll close this issue now, but feel free to comment again (or to create a new issue) if you need anything. Glad that I could help!
