### ISSUE TITLE
Every Event Logs "The event is not supported"

### ISSUE THREAD

**Issue by DKGames-MTDev** [Daniel-Brum/hacknplan-discord-integration#2]
All events report "The event  is not supported. Please disable it in your HackNPlan webhook." event the ones that are supposed to work.

**Comment by Daniel-Brum** [comment]
That's strange... events are working fine for me as of now. I think I'll add some proper debugging info on the "default event message" so it's easier to find out what went wrong.

**Comment by Daniel-Brum** [comment]
@DKGames-MTDev, do you mind testing it now? StickieBE's commit seems to fix that problem (thanks again!)

**Comment by DKGames-MTDev** [comment]
Unfortunately, same result.  Attempted moving task 2 times, created a new
task, and deleted it

[image: image.png]

**Comment by DKGames-MTDev** [comment]
Disregard my previous message.  It did work.  Thank you!
