### ISSUE TITLE
Web server host

### ISSUE THREAD

**Issue by Keromas** [Daniel-Brum/hacknplan-discord-integration#7]
Hi there, I can't really find any web server hosting services that allow me to use the files properly. Do you have any tracks of what kind of website could I use ?
I tried a few website but I can't copy any link from the files I uploaded on them to use them on the hack'n plan webhooks.

**Comment by Daniel-Brum** [comment]
The one I used before was https://www.000webhost.com and it worked well as far as I can remember. I'm sure there could be some other options too.

**Comment by Keromas** [comment]
Yeah I do found this web site but it seems that I can't obtain the right link to use the hach'n plan webhooks. Once I upload the files I can't get an external link to the translate_webhook_to_discord.php page. I'm blind or is it just not possible anymore? Thanks for the fast answer btw.

**Comment by Daniel-Brum** [comment]
It should be something like https://YOURSITENAME.000webhostapp.com/translate_webhook_to_discord.php I believe. I'll try to do it again and see if something has changed in the time I didn't use their site.

**Comment by Keromas** [comment]
Okay, there is progress actually. After a few manipulations, the hack'n plan webhook activity status succeeded ! But no message is sent by the discord webhook and when I download the attempt_log, here is what I found:
```
<br />
<b>Notice</b>:  Undefined index: X-Hacknplan-Event in <b>/storage/ssd4/400/20208400/public_html/translate_webhook_to_discord.php</b> on line <b>24</b><br />
Event not defined
```
Is there something I did wrong ? Or it's a bug due to an update from hack'n plan?

**Comment by Daniel-Brum** [comment]
I had pretty much the same problem when testing here. It is either a change in Hack'n'Plan's messages or in Discord's webhooks (though the latter seems less likely). I'll see if I can figure out what happened and how to solve it. Thanks for testing it!

**Comment by Keromas** [comment]
Okay, thanks a lot. Keep me in touch if you solve the issue.

**Comment by Dawid-Game** [comment]
Hi @Daniel-Brum  do we have some news about that problem?
I have the same bug as above :(

Thanks in advance :)

**Comment by Daniel-Brum** [comment]
Unfortunately not. I'm sorry. Didn't manage to find out much in this either, because work has been kinda difficult these last weeks. I'll try to contact Hack'n'Plan's devs and see if they know anything about it.

**Comment by Daniel-Brum** [comment]
@Keromas and @Dawid-Game, it should be working properly now. In the end it was a simple header name case problem, but I didn't think it was that at first; it was good to make contact with Hack'n'Plan's support.

They said that the header naming wasn't changed at all since like 2021 when it was first published, but we did have to change case in this integration service at some point after that, so something "in the middle" could be affecting the final name, and that's why they suggested casting the header name to lowercase or something like that and it then worked.

Please let me know if it works for you too, so that we can close this issue.

**Comment by Dawid-Game** [comment]
@Daniel-Brum  oooo nice <3 thank you, but could you be more specyfic what we should change to lowercase? Which line in which script?

**Comment by Daniel-Brum** [comment]
Just getting the latest commit should be enough, I've done the necessary changes in it. Hope it helps!

**Comment by Keromas** [comment]
It works perfectly! Thanks for your time and patience.

**Comment by Daniel-Brum** [comment]
That's good to know! I'll close the issue now, but feel free to reopen it or create a new one if needed.
