### ISSUE TITLE
Updates are populating with no data

### ISSUE THREAD

**Issue by Spartikus** [Daniel-Brum/hacknplan-discord-integration#8]
Evening Daniel. Thanks for this great plugin. Looks so simple. I am not sure if something is broken currently or how easy/hard it is to fix. Before I call HacknPlan support I thought I would check in.

When I perform an update, it triggers the discord correctly but there is no data to parse. So the webhook just posts the text for the case but no $data.xxxxx info.

Any suggestions would be outstanding. Thanks all

**Comment by Spartikus** [comment]
Just wanted to add that on the HnP side under the hooks area I can see it shows the data correctly so somthing isn't passing it to the php translator from what I can tell. Let me know if you would like a copy/paste of the webhook log from HnP.
edit: I have opened a ticket with HnP support to see if the headers have changed again. Will update once I hear from them.

**Comment by Daniel-Brum** [comment]
Hello! I didn't see this issue before, my bad! I'm about to go to bed right now, but give me a couple days and I'll take a look at this issue. Thanks for pointing it out!

**Comment by Spartikus** [comment]
Hey Daniel. Thanks for any insights. I havent heard back from HnP yet but I Assume it was a header structure change or something. I'll update here if I get any headway. I am sorry I cant be more helpful, normally I rip through the weblogs, look at the header and reverse engineer easily but my current webhost doesnt let me control or access the Web logs I need to see the syntax. (silly)

**Comment by Spartikus** [comment]
Hey Daniel, let me know if there is anything more I can do. I will try and reverse engineer the PHP this week and see if I can test on a different website with better logging and look at the data structure in the header. I assume its coming through the header. Thanks for any insight. I am still not sure if I did something wrong, my webhost is doing something wrong or this isnt working.

**Comment by Spartikus** [comment]
Okay spent a few hours last night digging into this. The issue that I can see if that the JSON decoding is returning a null. The web hook logs on the HacknPlan side show the JSON data but it appears the PHP input is either not being received by the script or something. I'll try some more coding tonight. Been 8 years since I used PHP :) Just want to confirm that the $JSON is getting populated. Was struggling with that last night.

It is all very possible I have just misconfigured something but I have tested both http and https incase of a redirect. I'll look for a couple more redirects like the www. etc. This is going to be fantastic when I get it working. Just need the JSON to come through.

**Comment by Spartikus** [comment]
Daniel stand down on this. I have done more tweaking and I now have data populating. I think it was a redirect. So sorry I wasn't able to dive harder into this and for any confusion. I will close this issue once I confirm the data is parsing. Right now I am definitely getting the JSON decoded.

**Comment by Spartikus** [comment]
Daniel I can confirm that the data is now fully populating. I am closing this issue as there never was a problem with your scripts. I love this tool and I am already customizing the heck out of it and it is wonderful. 

**Just for perfect clarity, this issue was with redirects on my webhost and nothing wrong with these scripts or the instructions**

Apologies for the distraction here. Great work!

**Comment by Daniel-Brum** [comment]
No problem! I was a bit busy with work so I didn't have too much time to fiddle around much, but I'm happy you could find a solution, and even happier the tool's being useful to you. Thanks for getting in touch!
